name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main






jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setting up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Validation Maven
        run: mvn -B -DskipTests=true validate

  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setting up JDK
        uses: actions/setup-java@v4
        with:
            java-version: 21
            distribution: 'temurin'
            cache: 'maven'
      - name: Testing the application
        run: mvn -B test package
      - name: Uploading JAR Artifact
        uses: actions/upload-artifact@v4
        with:
            name: app-jar
            path: target/*.jar
      - name: Uploading Test Reports
        uses: actions/upload-artifact@v4
        with:
            name: surefire-reports
            path: target/surefire-reports/**

